---
title: "billboard_data_wrangling"
author: "Ling"
date: "11/16/2021"
output: github_document
---

- The cleaned dataset

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)
library(kaggler)
library(haven)

kgl_auth(creds_file = 'kaggle.json')

response <- kgl_datasets_download_all(owner_dataset = "danield2255/data-on-songs-from-billboard-19992019")

download.file(response[["url"]], "data/temp.zip", mode = "wb")
unzip_result <- unzip("data/temp.zip", exdir = "./data", overwrite = TRUE)

billboard = read_csv("./data/BillboardFromLast20/billboardHot100_1999-2019.csv") %>%
  janitor::clean_names() %>%
  select(week,name,genre,lyrics) %>%
  mutate(year = format(week, "%Y"),
         lyrics = str_to_lower(str_replace(lyrics, "\n"," ")),
         genre = str_to_lower(genre)) %>%
  select(-week)

word_bank_genre_raw = pull(billboard, genre) %>%
  unlist() %>%
  unique() %>%
  as_tibble()

write.csv(word_bank_genre_raw, file = "./data/word_bank_genre_raw_ling.csv")

word_bank_raw = read_html("https://www.addictioncenter.com/drugs/drug-street-names/") %>%
  html_table(header = T)

word_bank_raw2 =  read_html("https://www.addictioncenter.com/drugs/drug-alcohol-slang/") %>%
  html_table(header = F) %>%
  .[-c(1,2,3)] %>%
  bind_rows() %>%
  select(X2) %>%
  mutate(slang = str_split(str_to_lower(X2), ',')) %>%
  select(slang) %>%
  unlist() %>%
  as_tibble()

word_bank_alcohol = read_html("https://www.addictioncenter.com/drugs/drug-alcohol-slang/") %>%
  html_table(header = F) %>%
  nth(2) %>%
  janitor::clean_names() %>%
  select(x2) %>%
  mutate(x2 = str_split(str_to_lower(x2), ',')) %>%
  unlist() %>%
  as_tibble()

write.csv(word_bank_alcohol, file = "./data/alcohol_bank_raw_ling.csv")

drug_bank <- function(raw , var) {
  out = raw %>%
  janitor::clean_names() %>%
  select({{var}}) %>%
  mutate(slang = str_split(str_to_lower({{var}}), ',')) %>%
  select(slang) %>%
  unlist() %>%
  as_tibble()
  return(out)
}

illicit_names = word_bank_raw[[3]] %>%
  janitor::clean_names()

word_bank_bdz = drug_bank(word_bank_raw[[1]], var = street_names)
word_bank_hallucinogens = drug_bank(word_bank_raw[[2]], var = street_names)
word_bank_inhalant = drug_bank(word_bank_raw[[4]], var = street_names)
word_bank_opioid = drug_bank(word_bank_raw[[5]], var = street_names)
word_bank_overcounter = drug_bank(word_bank_raw[[6]], var = street_names)
word_bank_marijuana = drug_bank(subset(illicit_names, common_name %in% c("Marijuana", "Synthetic Marijuana")), var = other_names)
word_bank_illicit = drug_bank(subset(illicit_names, !(common_name %in% c("Marijuana", "Synthetic Marijuana"))), var = other_names)
word_bank_other = bind_rows(word_bank_bdz, word_bank_hallucinogens, word_bank_illicit, word_bank_inhalant, word_bank_opioid, word_bank_overcounter, word_bank_raw2)
word_bank_marijuana2 = read_html("https://www.addictioncenter.com/drugs/drug-alcohol-slang/") %>%
  html_table(header = F) %>%
  nth(3) %>%
  select(X2) %>%
  mutate(slang = str_split(str_to_lower(X2), ',')) %>%
  unlist() %>%
  as_tibble()
word_bank_marijuana = bind_rows(word_bank_marijuana, word_bank_marijuana2)

write_csv(word_bank_other, file = "./data/other_illicit_bank_raw_ling.csv")
write_csv(word_bank_marijuana, file = "./data/marijuana_bank_raw_ling.csv")
```

Clean the manually classified music genre and alcohol word bank.
```{r}

genre = read_csv(file = "./data/word_bank_genre_code_ling.csv",
                         col_names = TRUE,
                         na = "") %>%
  select(-...1) %>%
  group_by(genre_cate) %>%
  summarise(subgenre = paste(value, collapse = "|")) %>%
  drop_na(genre_cate)

country = pull(subset(genre, genre_cate == "country"), subgenre)
hiphop = pull(subset(genre, genre_cate == "hip-hop/r&;b"), subgenre)
rap = pull(subset(genre, genre_cate == "rap"), subgenre)
rock = pull(subset(genre, genre_cate == "rock"), subgenre)


alcohol_summary = read_csv(file = "./data/alcohol_bank_code_ling.csv",
                           col_names = TRUE,
                           na = "") %>%
  select(-...1) %>%
  filter(is.na(delete)) %>%
  select(value)

write_csv(alcohol_summary, file = "./data/word_bank_alcohol_summary_ling.csv")
```
Load word banks
```{r}
alcohol = read_lines("./data/words/alcohol.csv") %>%
  paste(., collapse = "|")
weed = read_lines("./data/words/marijuana.csv") %>%
  paste(., collapse = "|")
other = read_lines("./data/words/other_illicit.csv") %>%
  paste(., collapse = "|")
```
Categorization
```{r}
billboard_1 = billboard %>%
  select(name, year, genre,lyrics) %>%
  mutate(lyr_alcohol = as.numeric(grepl(alcohol,lyrics,ignore.case = TRUE)),
         lyr_marijuana = as.numeric(grepl(weed, lyrics, ignore.case = TRUE)),
         lyr_other = as.numeric(grepl(other, lyrics, ignore.case = TRUE)),
         gen_country = as.numeric(grepl(country, genre, ignore.case = TRUE)),
         gen_hiphop = as.numeric(grepl(hiphop, genre, ignore.case = TRUE)),
         gen_rap = as.numeric(grepl(rap, genre, ignore.case = TRUE)),
         gen_rock = as.numeric(grepl(rock, genre, ignore.case = TRUE))) %>%
  select(-genre, -lyrics) 

write_csv(billboard_1, file = "./data/billboard_classification.csv", col_names = TRUE)
```


